# Generated by Django 4.1.6 on 2023-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_notes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
