# Generated by Django 4.1.6 on 2023-02-10 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_notes_date_modified_notes_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2023, 2, 10, 9, 35, 0, 950557)),
        ),
    ]
