# Generated by Django 4.1.6 on 2023-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_alter_notes_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
